### ISSUE TITLE
ValueError: Expected 2d Array, got scalar array

### ISSUE THREAD

**Issue by rajatsharma369007** [chaitjo/regression-stock-prediction#1]
in svr.py, inside the predict_price function

**Comment by rajatsharma369007** [comment]
resolved the issue, check out the pull request

**Comment by rajatsharma369007** [comment]
resolved the issue, check out the pull request

**Comment by chaitjo** [comment]
Thanks! Merged the PR. I have not been maintaining this project for over 3 years, so there might have been some issues with the python library versions.

Maybe you can add the exact python and library version you used for the benefit of future users of this code. :)
